add_newline = true
format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
[â”‚](bold green) $directory $git_branch $git_commit $git_status $nodejs $time
[â””â”€>](bold green)\
"""
scan_timeout = 10
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[package]
disabled = false

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = "î‚  "
style = "bold purple"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "
style = "bold white"

[git_status]
conflicted = "âš”ï¸ "
ahead      = " ğŸï¸ ğŸ’¨ Ã—${count}"
behind     = " ğŸ¢ Ã—${count}"
diverged   = " ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked  = " â“Ã—${count}"
stashed    = " ğŸ“¦ "
modified   = " ğŸ“Ã—${count}"
staged     = " ğŸ—ƒï¸ Ã—${count}"
renamed    = " ğŸ“› Ã—${count}"
deleted    = " ğŸ—‘ï¸ Ã—${count}"
style      = "bright-white"
format     = "$all_status$ahead_behind"

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[time]
disabled = false
format = '[\[$time\]]($style) '
